### ISSUE TITLE
02/labs/22 Task 5 `predict_linear(node_filesystem_avail_bytes[1h], 3600 * 4) < 0` => no data points?

### ISSUE THREAD

**Issue by johanngyger** [puzzle/prometheus-labs#62] opened 2021-01-02 19:54 UTC
The query doesn't show any data points. Is this the expected behaviour? Did I miss sth.?

**Comment by mabegglen** [comment] 2021-02-05 07:27
Duplicate of #65

**Closed by mabegglen** 2021-02-05 07:27 UTC
